"""init schema

Revision ID: a6b703e38e55
Revises: 
Create Date: 2025-11-10 22:24:43.628621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b703e38e55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_ad',
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('ad_group_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('final_urls', sa.JSON(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('ad_id')
    )
    op.create_index(op.f('ix_ads_ad_ad_group_id'), 'ads_ad', ['ad_group_id'], unique=False)
    op.create_table('ads_ad_group',
    sa.Column('ad_group_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('ad_group_id')
    )
    op.create_index(op.f('ix_ads_ad_group_campaign_id'), 'ads_ad_group', ['campaign_id'], unique=False)
    op.create_table('ads_campaign',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('channel_type', sa.String(length=64), nullable=True),
    sa.Column('bidding_strategy_type', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_ads_campaign_customer_id'), 'ads_campaign', ['customer_id'], unique=False)
    op.create_table('ads_customer',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('descriptive_name', sa.String(), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('manager', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('ads_daily_perf',
    sa.Column('perf_date', sa.Date(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('ad_group_id', sa.String(), nullable=True),
    sa.Column('ad_id', sa.String(), nullable=True),
    sa.Column('criterion_id', sa.String(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('conversions', sa.Float(), nullable=True),
    sa.Column('conversions_value', sa.Float(), nullable=True),
    sa.Column('interactions', sa.BigInteger(), nullable=True),
    sa.Column('interaction_rate', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('average_cpc_micros', sa.BigInteger(), nullable=True),
    sa.Column('average_cpm_micros', sa.BigInteger(), nullable=True),
    sa.Column('engagements', sa.BigInteger(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('video_views', sa.BigInteger(), nullable=True),
    sa.Column('video_view_rate', sa.Float(), nullable=True),
    sa.Column('all_conversions', sa.Float(), nullable=True),
    sa.Column('all_conversions_value', sa.Float(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('pulled_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('perf_date', 'level', 'customer_id', 'campaign_id', 'ad_group_id', 'ad_id', 'criterion_id')
    )
    op.create_table('ads_keyword',
    sa.Column('criterion_id', sa.String(), nullable=False),
    sa.Column('ad_group_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('criterion_id')
    )
    op.create_index(op.f('ix_ads_keyword_ad_group_id'), 'ads_keyword', ['ad_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_keyword_ad_group_id'), table_name='ads_keyword')
    op.drop_table('ads_keyword')
    op.drop_table('ads_daily_perf')
    op.drop_table('ads_customer')
    op.drop_index(op.f('ix_ads_campaign_customer_id'), table_name='ads_campaign')
    op.drop_table('ads_campaign')
    op.drop_index(op.f('ix_ads_ad_group_campaign_id'), table_name='ads_ad_group')
    op.drop_table('ads_ad_group')
    op.drop_index(op.f('ix_ads_ad_ad_group_id'), table_name='ads_ad')
    op.drop_table('ads_ad')
    # ### end Alembic commands ###
